algoritmo "semnome"
// Função :
// Autor :
// Data : 29/04/2022
// Seção de Declarações 
var
valor,total,juros:real
inicio
escreval("--------------------------------")
escreval("Deposite um valor")
leia(valor)
escreval("--------------------------------")
juros<-valor*0.7
total<-valor+juros
escreva("Seu saldo atual é: ")
escreval(total)
escreval("--------------------------------")
fimalgoritmo
