algoritmo "semnome"
// Função :
// Autor :
// Data : 29/04/2022
// Seção de Declarações
var
numero:real
i,contador:inteiro
inicio
para i de 1 ate 80 faca
   escreval("Escolha um número")
   leia(numero)
   se(numero>=10)entao
      se(numero<=150)entao
         contador<-contador+1
      fimse
   fimse
fimpara
escreva("A quantidade de números entre 10 e 150 foi ")
escreval(contador)
fimalgoritmo

