algoritmo "semnome"
// Função :
// Autor :
// Data : 29/04/2022
// Seção de Declarações
var
nome:caracter
nota1,nota2,nota3,media:real
inicio
escreval("Informe o nome do aluno: ")
leia(nome)
escreval("Digite a primeira nota: ")
leia(nota1)
escreval("Digite a segunda nota: ")
leia(nota2)
escreval("Digite a terceira nota: ")
leia(nota3)
media<-(nota1+nota2+nota3)/3
escreva("O aluno ")
escreva(nome)
escreva(" obteva a média ")
escreval(media)
fimalgoritmo
