algoritmo "semnome"
// Função :
// Autor :
// Data : 29/04/2022
// Seção de Declarações
var
numero:real
inicio
escreval("Escolha um número")
leia(numero)
se(numero>100)entao
   se(numero<200)entao
      escreval("O número está no intervalo")
   senao
      escreval("O número não está no intervalo")
   fimse
senao
   escreval("O número não está no intervalo")
fimse
fimalgoritmo

