algoritmo "semnome"
// Função :
// Autor :
// Data : 06/06/2022
// Seção de Declarações
var
nome:vetor[1..90] de caracter
i,k:inteiro
l:real
jogo:caracter
inicio
escreval("Informe o jogo")
leia(jogo)
escreval("Informe o número de participantes")
leia(k)
limpatela
para i de 1 ate k faca
escreval("Digite o nome do jogador")
leia(nome[i])
limpatela
fimpara
l <- k/2
aleatorio 1 ,k
para i de 1 ate l faca
escreval
fimalgoritmo
