algoritmo "semnome"
// Função :
// Autor :
// Data : 29/04/2022
// Seção de Declarações
var
z,k,l:inteiro
cadastro:caracter
inicio
cadastro<-"sim"
enquanto (cadastro="sim") faca
   escreval("Digite um número: ")
   leia(k)
   escreval("Quer adicionar outro número: ")
   leia(cadastro)
   se(k>l)entao
      l<-k
   fimse
fimenquanto
escreva("O maior número digitado foi: ")
escreval (l)
fimalgoritmo
